version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "54321:5432" 
    environment:
      POSTGRES_USER: allocation
      POSTGRES_PASSWORD: allocate
      POSTGRES_DB: allocation
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U allocation -d allocation"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=allocate
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
