version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "54321:5432" 
    environment:
      POSTGRES_USER: allocation
      POSTGRES_PASSWORD: allocate
      POSTGRES_DB: allocation
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=allocate
      - PYTHONPATH=/src
    volumes:
      - .:/src
    command: uvicorn src.run:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
