# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - task: test
      - task: isort
      - task: black

  test:
    cmds:
      - pytest --tb=short

  black:
    cmds:
      - black $(find * -name '*.py')

  isort:
    cmds:
      - isort .

  docker:up:
    cmds:
      - docker-compose up --build -d

  docker:down:
    cmds:
      - docker-compose down

  docker:test:
    cmds:
      - docker-compose run --rm api python -m pytest -v

  docker:clean:
    cmds:
      - docker-compose down -v
