apiVersion: v1
kind: Service
metadata:
  labels:
    app: salespilot
  name: salespilot
spec:
  type: NodePort
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: salespilot
